FROM nginx

COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./tools/init.sh ./init.sh
RUN chmod 755 init.sh

# make the private directory for ssl
RUN mkdir -p /etc/ssl/private
RUN chmod 700 /etc/ssl/private

EXPOSE 443

# CMD ['nginx', '-g', 'daemon off;']
CMD ["./init.sh"]