FROM node:21

WORKDIR /home/node/app

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# ENTRYPOINT ["/tini", "--"]

# Run your program under Tini
ENTRYPOINT ["./node_modules/.bin/http-server", "--proxy", "http://localhost:8080?"]