services:
  frontend:
    build: "./frontend"
    volumes:
      - ./frontend/public:/public
      - ./sslcert:/sslcert
    ports:
      - "443:443"

  backend:
    build: "./backend"
    tty: true
    depends_on:
      - db
    networks:
      - frontend_net
      - backend_net
    working_dir: "/app"
    volumes:
      - ./backend/src:/app
      - ./sslcert:/sslcert
    ports:
      - "8000:443"
    env_file:
      - .env
    expose:
      - "443"

  db:
    image: postgres
    env_file:
      - .env
    networks:
      - backend_net
    volumes:
      - ./data/database:/var/lib/postgresql/data
    expose:
      - "5432"

  postgresql-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./devops/pg-exporter/pg-exporter.yml:/pg-exporter.yml
    command:
      - '--config.file=/pg-exporter.yml'
    expose:
      - "9187"
    depends_on:
      - db
    networks:
      - backend_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./devops/prometheus/rules.rules:/etc/prometheus/rules.rules
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.external-url=http://localhost:9090/'
    depends_on:
      - postgresql-exporter
      - backend
      - alertmanager
    networks:
      - backend_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./devops/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./devops/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - backend_net

  alertmanager:
    image: quay.io/prometheus/alertmanager
    ports:
      - 9093:9093
    networks:
      - backend_net
    volumes:
      - './devops/alertmanager/mailing-alertmanager.yml:/alertmanager.yml'
    command:
      - '--config.file=/alertmanager.yml'

volumes:
  prometheus-data: {}
  grafana-storage: {}

networks:
  frontend_net:
  backend_net: