FROM python:latest

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .
COPY ./script.bash .
RUN chmod +x ./script.bash

CMD ["./script.bash"]
