route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 1m
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://127.0.0.1:9093/alerts'