# NOTE: THIS IS NEVER EXPECTED TO BE USED
# USE THE SPECIAL VARIANT INSTEAD
# THIS IS BECAUSE WE CANNOT PASS IN ENV VALUE TO .yml FILES
# AND WE CANNOT CREATE NEW FILES IN THE DOCKER CONTAINER
# SO WE ARE BASICALLY FORCED TO DO THIS

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 1m
  receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'https://localhost:8000/api/alert'
