# Generated by Django 4.1 on 2024-06-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_player_friends_alter_player_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='from_player',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='to_player',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='database.player'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='database.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./backend/src/assets/firefly.png', upload_to=''),
        ),
    ]
