# Generated by Django 4.1 on 2024-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_friend_request_from_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./firefly.png', upload_to=''),
        ),
    ]
