global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['host.docker.internal:9093']

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['127.0.0.1:9090']

- job_name: transcendence
  metrics_path: '/metrics'
  static_configs:
  - targets: ['host.docker.internal:8000']
  tls_config:
      insecure_skip_verify: true
